# Generated by Django 6.0.2 on 2026-02-11 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['route_name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['type_name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('document_date', models.DateField()),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('current_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('finalized', 'Finalized')], default='pending', max_length=20)),
                ('current_location', models.CharField(blank=True, max_length=100)),
                ('is_finalized', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documenttype')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.route')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint_name', models.CharField(max_length=100)),
                ('sequence_order', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('receiver_name', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_checkpoints', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='documents.document')),
            ],
            options={
                'ordering': ['document', 'sequence_order'],
                'unique_together': {('document', 'sequence_order')},
            },
        ),
        migrations.CreateModel(
            name='CheckpointTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint_name', models.CharField(max_length=100)),
                ('sequence_order', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='documents.documenttype')),
            ],
            options={
                'ordering': ['document_type', 'sequence_order'],
                'unique_together': {('document_type', 'sequence_order')},
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tracking_id'], name='documents_d_trackin_848a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type', 'route'], name='documents_d_documen_cd945c_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['current_status'], name='documents_d_current_504e43_idx'),
        ),
    ]
